### ISSUE TITLE
"Cannot find module" when running npm start for v2.0.0 on Windows 10

### ISSUE THREAD

**Issue by jacobstern** [Hashnode/mern-starter#170] opened 2016-06-21 07:36 UTC
Hi all, I am running Node v6.2.2 and npm 3.9.6 on Windows 10 Preview build 14366.

I did a clean install of the starter repo - both by cloning the repo and also using the CLI, which apparently now uses v2.0.0. When I hit "npm start" I get the following error. It seems like there is some issue with how file paths are setup.

I'm new to the JavaScript tooling space so I'm not sure how to debug. Any thoughts or workarounds would be appreciated.
```

module.js:442
    throw err;
    ^

Error: Cannot find module 'C:\Users\Jacob\OneDrive\Documents\mern-app\C\:\Users\Jacob\OneDrive\Documents\mern-app\node_modules\webpack\bin\webpack.js'
    at Function.Module._resolveFilename (module.js:440:15)
    at Function.Module._load (module.js:388:25)
    at Module.runMain (module.js:575:10)
    at run (node.js:348:7)
    at startup (node.js:140:9)
    at node.js:463:3
C:\Users\Jacob\OneDrive\Documents\mern-app\node_modules\babel-core\lib\transformation\file\index.js:591
      throw err;
      ^

Error: C:/Users/Jacob/OneDrive/Documents/mern-app/client/modules/App/App.js: Command failed: node C\:\\Users\\Jacob\\OneDrive\\Documents\\mern-app\\node_modules\\webpack\\bin\\webpack.js C\:\\Users\\Jacob\\OneDrive\\Documents\\mern-app\\client\\modules\\App\\App.css C\:\\Users\\Jacob\\AppData\\Local\\Temp\\.webpack.res.1466494094898_296377.js --config ./webpack.config.babel.js --bail
module.js:442
    throw err;
    ^

Error: Cannot find module 'C:\Users\Jacob\OneDrive\Documents\mern-app\C\:\Users\Jacob\OneDrive\Documents\mern-app\node_modules\webpack\bin\webpack.js'
    at Function.Module._resolveFilename (module.js:440:15)
    at Function.Module._load (module.js:388:25)
    at Module.runMain (module.js:575:10)
    at run (node.js:348:7)
    at startup (node.js:140:9)
    at node.js:463:3

    at checkExecSyncError (child_process.js:486:13)
    at execSync (child_process.js:526:13)
    at exports.default (C:\Users\Jacob\OneDrive\Documents\mern-app\node_modules\babel-plugin-webpack-loaders\lib\runWebPackSync.js:41:51)
    at PluginPass.CallExpression (C:\Users\Jacob\OneDrive\Documents\mern-app\node_modules\babel-plugin-webpack-loaders\lib\plugin.js:93:60)
    at newFn (C:\Users\Jacob\OneDrive\Documents\mern-app\node_modules\babel-traverse\lib\visitors.js:310:19)
    at NodePath._call (C:\Users\Jacob\OneDrive\Documents\mern-app\node_modules\babel-traverse\lib\path\context.js:78:18)
    at NodePath.call (C:\Users\Jacob\OneDrive\Documents\mern-app\node_modules\babel-traverse\lib\path\context.js:49:17)
    at NodePath.visit (C:\Users\Jacob\OneDrive\Documents\mern-app\node_modules\babel-traverse\lib\path\context.js:108:12)
    at TraversalContext.visitQueue (C:\Users\Jacob\OneDrive\Documents\mern-app\node_modules\babel-traverse\lib\context.js:174:16)
    at TraversalContext.visitSingle (C:\Users\Jacob\OneDrive\Documents\mern-app\node_modules\babel-traverse\lib\context.js:124:19)
    at TraversalContext.visit (C:\Users\Jacob\OneDrive\Documents\mern-app\node_modules\babel-traverse\lib\context.js:219:19)
    at Function.traverse.node (C:\Users\Jacob\OneDrive\Documents\mern-app\node_modules\babel-traverse\lib\index.js:171:17)
    at NodePath.visit (C:\Users\Jacob\OneDrive\Documents\mern-app\node_modules\babel-traverse\lib\path\context.js:118:43)
    at TraversalContext.visitQueue (C:\Users\Jacob\OneDrive\Documents\mern-app\node_modules\babel-traverse\lib\context.js:174:16)
    at TraversalContext.visitMultiple (C:\Users\Jacob\OneDrive\Documents\mern-app\node_modules\babel-traverse\lib\context.js:119:17)
    at TraversalContext.visit (C:\Users\Jacob\OneDrive\Documents\mern-app\node_modules\babel-traverse\lib\context.js:217:19)
    at Function.traverse.node (C:\Users\Jacob\OneDrive\Documents\mern-app\node_modules\babel-traverse\lib\index.js:171:17)
```

**Comment by SOSANA** [comment] 2016-06-21 23:53
Having similar problem on windows...(sigh)

**Comment by arguser** [comment] 2016-06-22 12:05
I had the same issue, the output points out that webpack is missing. I've tried with a `npm install webpack` which lead me to the issue responsible for not having it installed in the first place and seems to be related with MSBuild/VCBuild solely a Windows matter.

My first attempt to solve this issue is to check and install specific dependencies for [node-gyp](https://www.npmjs.com/package/node-gyp), I will update you with some results of this approach this afternoon.

**Comment by pointnet** [comment] 2016-06-22 12:56
Same issue here, error is coming from babel-plugin-webpack-loaders.

It use node-shell-quote to generate `node C\:\\Users\\Jacob\\OneDrive\\Documents\\mern-app\\node_modules\\webpack\\bin\\webpack.js` and this definitly cannot work in a windows command process.

**Comment by jacobstern** [comment] 2016-06-22 17:48
@arguser I found [this thread](https://github.com/nodejs/node-gyp/issues/629#issuecomment-153196245) resolved my issues installing node-gyp on Windows when I was having trouble earlier. Not sure that's the issue here though since I can install node-gyp fine now.

**Comment by arguser** [comment] 2016-06-22 18:18
@jacobstern Exactly, it's a similar suggestion since regards on node-gyp dependencies. I followed the instructions of the package and worked but I still have problems with webpack.

**Comment by arguser** [comment] 2016-06-22 20:08
Tried on linux:

`npm ERR! Linux 4.4.0-21-generic
npm ERR! argv "/usr/bin/nodejs" "/usr/bin/npm" "install"
npm ERR! node v4.4.5
npm ERR! npm  v2.15.5
npm ERR! code EPEERINVALID

npm ERR! peerinvalid The package webpack@2.1.0-beta.13 does not satisfy its siblings' peerDependencies requirements!
npm ERR! peerinvalid Peer babel-loader@6.2.4 wants webpack@1 || ^2.1.0-beta
npm ERR! peerinvalid Peer extract-text-webpack-plugin@1.0.1 wants webpack@^1.9.11
npm ERR! peerinvalid Peer chunk-manifest-webpack-plugin@0.1.0 wants webpack@^1.4.0-beta6
npm ERR! peerinvalid Peer webpack-dev-middleware@1.6.1 wants webpack@1 || ^2.1.0-beta
npm ERR! peerinvalid Peer babel-plugin-webpack-loaders@0.5.0 wants webpack@>=1.12.9 Emoticón heart.0.0
npm ERR! peerinvalid Peer webpack-dev-server@2.1.0-beta.0 wants webpack@^2.1.0-beta

npm ERR! Please include the following file with any support request:
npm ERR!     /home/arguser/Documentos/Tranquera/ysyry/npm-debug.log`

**Comment by jacobstern** [comment] 2016-06-22 20:40
Returning to the initial topic, has anyone been successful running v2 on Windows?

**Comment by pointnet** [comment] 2016-06-22 22:04
I made it run by patching `babel-plugin-webpack-loaders`.
Open `~\node_modules\babel-plugin-webpack-loaders\lib\runWebPackSync.js`
Go to line 41, replace
`var webPackStdOut = (0, _child_process.execSync)((0, _shellQuote.quote)(['node', // for windows support
webPackPath, path, outPath, '--config', configPath, '--bail']));`
with
`var webPackStdOut = (0, _child_process.execSync)(['node', // for windows support
webPackPath, path, outPath, '--config', configPath, '--bail'].join(' '));
Voila!

**Comment by pointnet** [comment] 2016-06-22 22:14
@arguser to fix your issue with peerDependencies, please update npm up to 3.0 with `npm install -g npm@next` and try again :)

**Comment by SOSANA** [comment] 2016-06-22 22:27
@pointnet gonna try and report back if this works, if this does solve problem than you should open pr as this is a bug with ```babel-plugin-webpack-loaders```

**Comment by SOSANA** [comment] 2016-06-22 22:57
@pointnet  confirmed this did in fact work following directions above!

@somus @prank7 @sandeeppanda92 @mayankchd thoughts on how we should tackle fixing this? should @pointnet open pr with ```babel-plugin-webpack-loaders``` ?

**Comment by SOSANA** [comment] 2016-06-22 23:12
Hi all, as shown above opened an issue....

**Comment by SOSANA** [comment] 2016-06-23 01:51
Update: PR waiting for review and merge [here](https://github.com/istarkov/babel-plugin-webpack-loaders/pull/107)

Current babel-plugin-webpack-loaders v0.6.1

**Comment by somus** [comment] 2016-06-23 01:53
@pointnet Thanks for finding out the root cause. @SOSANA Awesome! Once that PR is accepted, I'll update package.json.

**Comment by SOSANA** [comment] 2016-06-23 01:54
@pointnet @somus on stand by :+1:

**Comment by SOSANA** [comment] 2016-06-23 05:55
@pointnet @somus merged and should be published today as per PR [107](https://github.com/istarkov/babel-plugin-webpack-loaders/pull/107)

**Comment by pointnet** [comment] 2016-06-23 06:59
@SOSANA Awesome!
@somus You're welcome!

**Comment by SOSANA** [comment] 2016-06-23 07:01
@somus @pointnet new npm has been published, all we need to do is update package.json with babel-plugin-webpack-loaders v0.7.0.............schweet!!!

**Comment by SOSANA** [comment] 2016-06-23 07:50
@somus ready for merge as per PR #176

**Comment by somus** [comment] 2016-06-23 07:57
@SOSANA Merged. 👍

**Closed by somus** 2016-06-23 07:57 UTC

**Comment by stephan281094** [comment] 2016-06-23 08:19
Nice work @SOSANA! 👍

**Comment by jacobstern** [comment] 2016-06-23 17:56
Awesome work @SOSANA and @pointnet! Thanks!

**Comment by anjain** [comment] 2017-03-07 11:05
any body can help me to minify aap.js for react

**Comment by codeuniquely** [comment] 2017-09-01 09:22
have the same issue when running on Mac (never been near a windows environment) with, 

"webpack": "3.5.5",

tried also using lastest version of loaders too .....
"babel-plugin-webpack-loaders": "^0.9.0",

**Comment by EzgiTetik** [comment] 2018-07-03 09:16
@codeuniquely same problem but on Windows. Did you find the solution?
