### ISSUE TITLE
Does not work when Upgraded to React v16 and React-router v4.

### ISSUE THREAD

**Issue by chaudharykiran** [Hashnode/mern-starter#333] opened 2017-10-07 17:53 UTC

**Comment by Ballpin** [comment] 2017-10-15 17:07
I have been working on a new mern stack insipred from mern-starter and react-universally. The stable version is still on 15 though. But i have a branch for react 16 with react router 4, the only thing that is not working is the tests because react-addons-test-utils needs to be changed.

The url for it is https://github.com/Ballpin/mern-starter2

**Comment by mannyhenri** [comment] 2018-06-01 23:50
Duplicate of #330 and we'll thoroughly test it before we release it.

**Closed by mannyhenri** 2018-06-01 23:50 UTC
Labels: duplicate
