### ISSUE TITLE
npm test broken out of the box

### ISSUE THREAD

**Issue by pzenger** [Hashnode/mern-starter#216] opened 2016-07-27 21:24 UTC
After installing MERN, running `npm test` results in 4 errors which look like the following

`3. Unhandled Rejection
   ValidationError: Path `slug` is required.`

**Comment by cuongquay** [comment] 2016-07-31 17:26
The same error using env

npm ERR! Darwin 15.5.0
npm ERR! argv "/usr/local/Cellar/node/6.3.0/bin/node" "/usr/local/bin/npm" "run" "test"
npm ERR! node v6.3.0
npm ERR! npm  v3.10.3

**Comment by simonwalsh** [comment] 2016-08-05 15:39
Same here! Will try to fix.

**Comment by cuongquay** [comment] 2016-08-07 03:01
[patch.txt](https://github.com/Hashnode/mern-starter/files/405280/patch.txt)

I have just fixed it by changing the mockgoose version as well as webpack version

**Comment by gihrig** [comment] 2016-08-10 06:39
I just installed mern-starter, got the errors described, made the dependency updates suggested by @cuongquay, removed `node_modules` then `npm install`.

I still get the `ValidationError: Path `slug` is required.` errors on `npm test`.

Any other ideas?

**Comment by somus** [comment] 2016-08-10 08:43
Can you post the full error stack? Also, which operating system are you using?

**Comment by gihrig** [comment] 2016-08-10 17:58
@somus 
Mac OS 10.11.6
node -v v6.3.1
npm -v 3.10.5
```
:mern-starter glen$ npm test

> mern-starter@2.0.0 test /Users/glen/Documents/JavaScript/Research/mern-starter
> cross-env NODE_ENV=test PORT=8080 MONGO_URL=mongodb://localhost:27017/mern-test node_modules/.bin/nyc node --harmony-proxies node_modules/.bin/ava

MERN is running on port: 8080! Build something amazing!
Warning: Failed prop type: Required prop `intl` was not specified in `PostCreateWidget`.
    in PostCreateWidget
[React Intl] Missing message: "createNewPost" for locale: "en"
[React Intl] Cannot format message: "createNewPost", using message id as fallback.
[React Intl] Missing message: "submit" for locale: "en"
[React Intl] Cannot format message: "submit", using message id as fallback.
[React Intl] Missing message: "by" for locale: "en"
[React Intl] Cannot format message: "by", using message id as fallback.
[React Intl] Missing message: "switchLanguage" for locale: "en"
[React Intl] Cannot format message: "switchLanguage", using message id as fallback.
[React Intl] Missing message: "deletePost" for locale: "en"
[React Intl] Cannot format message: "deletePost", using message id as fallback.
[React Intl] Missing message: "siteTitle" for locale: "en"
[React Intl] Cannot format message: "siteTitle", using message id as fallback.
[React Intl] Missing message: "addPost" for locale: "en"
[React Intl] Cannot format message: "addPost", using message id as fallback.
[React Intl] Missing message: "twitterMessage" for locale: "en"
[React Intl] Cannot format message: "twitterMessage", using message id as fallback.
[React Intl] Missing message: "createNewPost" for locale: "en"
[React Intl] Cannot format message: "createNewPost", using message id as fallback.
[React Intl] Missing message: "submit" for locale: "en"
[React Intl] Cannot format message: "submit", using message id as fallback.
[React Intl] Missing message: "createNewPost" for locale: "en"
[React Intl] Cannot format message: "createNewPost", using message id as fallback.
[React Intl] Missing message: "submit" for locale: "en"
[React Intl] Cannot format message: "submit", using message id as fallback.
[React Intl] Missing message: "createNewPost" for locale: "en"
[React Intl] Cannot format message: "createNewPost", using message id as fallback.
[React Intl] Missing message: "submit" for locale: "en"
[React Intl] Cannot format message: "submit", using message id as fallback.

   36 passed
   4 rejections


   1. Unhandled Rejection
   ValidationError: Path `slug` is required.
    MongooseError.ValidationError (/Users/glen/Documents/JavaScript/Research/mern-starter/node_modules/mongoose/lib/error/validation.js:22:11)
    model.Document.invalidate (/Users/glen/Documents/JavaScript/Research/mern-starter/node_modules/mongoose/lib/document.js:1410:32)
    /Users/glen/Documents/JavaScript/Research/mern-starter/node_modules/mongoose/lib/document.js:1286:17
    validate (/Users/glen/Documents/JavaScript/Research/mern-starter/node_modules/mongoose/lib/schematype.js:707:7)
    /Users/glen/Documents/JavaScript/Research/mern-starter/node_modules/mongoose/lib/schematype.js:744:9
    SchemaString.SchemaType.doValidate (/Users/glen/Documents/JavaScript/Research/mern-starter/node_modules/mongoose/lib/schematype.js:712:19)
    /Users/glen/Documents/JavaScript/Research/mern-starter/node_modules/mongoose/lib/document.js:1284:9
    _combinedTickCallback (internal/process/next_tick.js:67:7)
    process._tickCallback (internal/process/next_tick.js:98:9)


   2. Unhandled Rejection
   ValidationError: Path `slug` is required.
    MongooseError.ValidationError (/Users/glen/Documents/JavaScript/Research/mern-starter/node_modules/mongoose/lib/error/validation.js:22:11)
    model.Document.invalidate (/Users/glen/Documents/JavaScript/Research/mern-starter/node_modules/mongoose/lib/document.js:1410:32)
    /Users/glen/Documents/JavaScript/Research/mern-starter/node_modules/mongoose/lib/document.js:1286:17
    validate (/Users/glen/Documents/JavaScript/Research/mern-starter/node_modules/mongoose/lib/schematype.js:707:7)
    /Users/glen/Documents/JavaScript/Research/mern-starter/node_modules/mongoose/lib/schematype.js:744:9
    SchemaString.SchemaType.doValidate (/Users/glen/Documents/JavaScript/Research/mern-starter/node_modules/mongoose/lib/schematype.js:712:19)
    /Users/glen/Documents/JavaScript/Research/mern-starter/node_modules/mongoose/lib/document.js:1284:9
    _combinedTickCallback (internal/process/next_tick.js:67:7)
    process._tickCallback (internal/process/next_tick.js:98:9)


   3. Unhandled Rejection
   ValidationError: Path `slug` is required.
    MongooseError.ValidationError (/Users/glen/Documents/JavaScript/Research/mern-starter/node_modules/mongoose/lib/error/validation.js:22:11)
    model.Document.invalidate (/Users/glen/Documents/JavaScript/Research/mern-starter/node_modules/mongoose/lib/document.js:1410:32)
    /Users/glen/Documents/JavaScript/Research/mern-starter/node_modules/mongoose/lib/document.js:1286:17
    validate (/Users/glen/Documents/JavaScript/Research/mern-starter/node_modules/mongoose/lib/schematype.js:707:7)
    /Users/glen/Documents/JavaScript/Research/mern-starter/node_modules/mongoose/lib/schematype.js:744:9
    SchemaString.SchemaType.doValidate (/Users/glen/Documents/JavaScript/Research/mern-starter/node_modules/mongoose/lib/schematype.js:712:19)
    /Users/glen/Documents/JavaScript/Research/mern-starter/node_modules/mongoose/lib/document.js:1284:9
    _combinedTickCallback (internal/process/next_tick.js:67:7)
    process._tickCallback (internal/process/next_tick.js:98:9)


   4. Unhandled Rejection
   ValidationError: Path `slug` is required.
    MongooseError.ValidationError (/Users/glen/Documents/JavaScript/Research/mern-starter/node_modules/mongoose/lib/error/validation.js:22:11)
    model.Document.invalidate (/Users/glen/Documents/JavaScript/Research/mern-starter/node_modules/mongoose/lib/document.js:1410:32)
    /Users/glen/Documents/JavaScript/Research/mern-starter/node_modules/mongoose/lib/document.js:1286:17
    validate (/Users/glen/Documents/JavaScript/Research/mern-starter/node_modules/mongoose/lib/schematype.js:707:7)
    /Users/glen/Documents/JavaScript/Research/mern-starter/node_modules/mongoose/lib/schematype.js:744:9
    SchemaString.SchemaType.doValidate (/Users/glen/Documents/JavaScript/Research/mern-starter/node_modules/mongoose/lib/schematype.js:712:19)
    /Users/glen/Documents/JavaScript/Research/mern-starter/node_modules/mongoose/lib/document.js:1284:9
    _combinedTickCallback (internal/process/next_tick.js:67:7)
    process._tickCallback (internal/process/next_tick.js:98:9)
```

**Comment by jxodwyer** [comment] 2016-08-17 02:43
The test suite seems to be crashing while watching (may be related to this)

output is:

```

1. Uncaught Exception
   TypeError: callback is not a function
    start (/Users/jamesodwyer/Desktop/hack/astronaute/node_modules/mongodb-prebuilt/index.js:83:13)
    Object.start_server (/Users/jamesodwyer/Desktop/hack/astronaute/node_modules/mongodb-prebuilt/index.js:69:16)
    /Users/jamesodwyer/Desktop/hack/astronaute/node_modules/mockgoose/Mockgoose.js:144:42
    next (/Users/jamesodwyer/Desktop/hack/astronaute/node_modules/rimraf/rimraf.js:74:7)
    CB (/Users/jamesodwyer/Desktop/hack/astronaute/node_modules/rimraf/rimraf.js:110:9)
    /Users/jamesodwyer/Desktop/hack/astronaute/node_modules/rimraf/rimraf.js:136:14
    FSReqWrap.oncomplete (fs.js:123:15)


   ✖ Test results were not received from server/models/__tests__/post.spec.js

```

Ava seems to be calling it out as well: https://github.com/mccormicka/Mockgoose/issues/204

**Comment by WillLuce** [comment] 2016-09-14 04:16
Seeing this too.

**Comment by mannyhenri** [comment] 2018-06-02 05:20
@MrChristofferson up to take a look at the test issues? This issue might be related to #250

**Comment by mattlubner** [comment] 2018-06-03 21:40
I'm unable to reproduce this… would strongly suspect it was fixed in any one of the several commits to `master` since the issue was reported. Closing as a result.

**Closed by mattlubner** 2018-06-03 21:40 UTC
Labels: V2.5.0, bug
