### ISSUE TITLE
Hot reloading takes too much time

### ISSUE THREAD

**Issue by HaiderMalik12** [Hashnode/mern-starter#307] opened 2017-05-06 05:43 UTC
Hot reloading takes too much time. When i change any file on server it takes two or three minutes to reload the content and start server again

**Comment by enginaryum** [comment] 2017-06-02 01:05
Same here, already tried some isomorphic webpack packages to transpile seperately but couldn't succeed yet.

**Comment by mannyhenri** [comment] 2018-06-03 22:00
@mattlubner I suspect with the udpated webpack we don't have this issue anymore, did you see differently?

**Comment by mattlubner** [comment] 2018-06-03 22:02
This strikes me as a possible duplicate of #153 ?

**Comment by mannyhenri** [comment] 2018-06-03 22:04
@mattlubner yes it is...closing

**Closed by mannyhenri** 2018-06-03 22:04 UTC
Labels: duplicate
