### ISSUE TITLE
Chunk.entry was removed. Use hasRuntime()

### ISSUE THREAD

**Issue by colinshen** [Hashnode/mern-starter#200] opened 2016-07-14 17:41 UTC
When I run bs to build my project I got this error

```
ERROR in chunk vendor [entry]
app.49e93b4e8d0733ad1108.js
Chunk.entry was removed. Use hasRuntime()
```

I tried to update webpack@^2.1.0-beta.17 + extract-text-webpack-plugin@^2.0.0-beta which talked in this [webpack issue](https://github.com/webpack/webpack/issues/2764) I still get this error.

**Comment by smallseven1213** [comment] 2016-07-15 16:31
me, too.

please help.

**Comment by colinshen** [comment] 2016-07-19 07:26
i have waited for a few days..any solution?

**Comment by tayzlor** [comment] 2016-07-19 07:40
confirmed i'm hitting this issue as well updating webpack (^2.1.0-beta-19) and extract-text-webpack-plugin (^2.0.0-beta) (with the corresponding updates required in the webpack.config files)

**Comment by colinshen** [comment] 2016-07-20 02:27
@tayzlor do you now which version I can use?

**Comment by somus** [comment] 2016-07-21 04:04
There is some problem with the new versions of webpack and extract-text-plugin. I couldn't get it to work. I'll investigate more. In the meantime, revert back to `webpack@2.1.0-beta.8` and `extract-text-webpack-plugin@1.0.1`.

**Comment by maciejmyslinski** [comment] 2016-07-21 12:36
Thank you for the tip, @somus. I really appreciate this starter kit. However, when I've followed your advice I got the following error:

```bash
ERROR in ./client/App.js
Module not found: Error: Can't resolve '[object Object]' in '/Users/Maciej/Projects/robson/kalkulator-sprezyn-2'
 @ ./client/App.js 15:0-21

ERROR in ./client/modules/App/App.js
Module not found: Error: Can't resolve '[object Object]' in '/Users/Maciej/Projects/robson/kalkulator-sprezyn-2'
 @ ./client/modules/App/App.js 15:0-31

ERROR in ./client/modules/Post/pages/PostDetailPage/PostDetailPage.js
Module not found: Error: Can't resolve '[object Object]' in '/Users/Maciej/Projects/robson/kalkulator-sprezyn-2'
 @ ./client/modules/Post/pages/PostDetailPage/PostDetailPage.js 9:0-68

ERROR in ./client/modules/App/components/Header/Header.js
Module not found: Error: Can't resolve '[object Object]' in '/Users/Maciej/Projects/robson/kalkulator-sprezyn-2'
 @ ./client/modules/App/components/Header/Header.js 8:0-34

ERROR in ./client/modules/App/components/Footer/Footer.js
Module not found: Error: Can't resolve '[object Object]' in '/Users/Maciej/Projects/robson/kalkulator-sprezyn-2'
 @ ./client/modules/App/components/Footer/Footer.js 7:0-34

ERROR in ./client/modules/Post/components/PostCreateWidget/PostCreateWidget.js
Module not found: Error: Can't resolve '[object Object]' in '/Users/Maciej/Projects/robson/kalkulator-sprezyn-2'
 @ ./client/modules/Post/components/PostCreateWidget/PostCreateWidget.js 15:0-44

ERROR in ./client/modules/Post/components/PostListItem/PostListItem.js
Module not found: Error: Can't resolve '[object Object]' in '/Users/Maciej/Projects/robson/kalkulator-sprezyn-2'
 @ ./client/modules/Post/components/PostListItem/PostListItem.js 8:0-40
```

Maby some adjustments in the code are needed?

**Comment by maciejmyslinski** [comment] 2016-07-21 12:47
Ok, I had to update `webpack.config.prod.js` because `extract-text-webpack-plugin`'s API has changed in v.2
Now `npm run build` works like a harm.
However `npm run build:server` fails with this error:
```bash
ERROR in ./client/modules/App/App.css
Module parse failed: /Users/Maciej/Projects/robson/kalkulator-sprezyn-2/client/modules/App/App.css Unexpected token (1:0)
You may need an appropriate loader to handle this file type.
| .container {
|   max-width: 980px;
|   width: 100%;
 @ ./client/modules/App/App.js 15:0-31

ERROR in ./client/modules/Post/components/PostListItem/PostListItem.css
Module parse failed: /Users/Maciej/Projects/robson/kalkulator-sprezyn-2/client/modules/Post/components/PostListItem/PostListItem.css Unexpected token (1:0)
You may need an appropriate loader to handle this file type.
| .single-post {
|   margin: 20px 0;
|   padding: 15px;
 @ ./client/modules/Post/pages/PostDetailPage/PostDetailPage.js 9:0-68

ERROR in ./client/modules/App/components/Header/Header.css
Module parse failed: /Users/Maciej/Projects/robson/kalkulator-sprezyn-2/client/modules/App/components/Header/Header.css Unexpected token (1:0)
You may need an appropriate loader to handle this file type.
| .header {
|   background: #eee url('../../header-bk.png') center;
|   background-size: cover;
 @ ./client/modules/App/components/Header/Header.js 8:0-34

ERROR in ./client/modules/App/header-bk.png
Module parse failed: /Users/Maciej/Projects/robson/kalkulator-sprezyn-2/client/modules/App/header-bk.png Unexpected character '�' (1:0)
You may need an appropriate loader to handle this file type.
(Source code omitted for this binary file)
 @ ./client/modules/App/components/Footer/Footer.js 10:0-37

ERROR in ./client/modules/App/components/Footer/Footer.css
Module parse failed: /Users/Maciej/Projects/robson/kalkulator-sprezyn-2/client/modules/App/components/Footer/Footer.css Unexpected token (1:0)
You may need an appropriate loader to handle this file type.
| .footer{
|   text-align: center;
|   padding: 56px 0;
 @ ./client/modules/App/components/Footer/Footer.js 7:0-34

ERROR in ./client/modules/Post/components/PostCreateWidget/PostCreateWidget.css
Module parse failed: /Users/Maciej/Projects/robson/kalkulator-sprezyn-2/client/modules/Post/components/PostCreateWidget/PostCreateWidget.css Unexpected token (1:0)
You may need an appropriate loader to handle this file type.
| .form {
|   display: none;
|   background: #FAFAFA;
 @ ./client/modules/Post/components/PostCreateWidget/PostCreateWidget.js 15:0-44
```

**Comment by vwrobel** [comment] 2016-07-22 14:27
@maciejmyslinski: After changing my `webpack.config.prod.js`, I had the same erros with `npm run build:server`. I was able to go one step further with the following changes to my package.json file:

```
-    "chunk-manifest-webpack-plugin": "0.1.0",
+    "chunk-manifest-webpack-plugin": "brandondoran/chunk-manifest-webpack-2",
-    "extract-text-webpack-plugin": "^1.0.1",
+    "extract-text-webpack-plugin": "^2.0.0-beta",
-    "webpack": "^2.1.0-beta.8",
+    "webpack": "^2.1.0-beta.20",
```

You can have a look at [this issue in chunk-manifest-webpack-plugin](Plugin errors in webpack 2 #12).

Now I get the following error: 

```
> mern-starter@2.0.0 build:server /Users/vwrobel/Projets/myApp
> cross-env BABEL_DISABLE_CACHE=1 NODE_ENV=production webpack --config webpack.config.server.js

/Users/vwrobel/Projets/myApp/node_modules/webpack-externals-plugin/index.js:19
              data.dependency.request,
                             ^

TypeError: Cannot read property 'request' of undefined
    at /Users/vwrobel/Projets/myApp/node_modules/webpack-externals-plugin/index.js:19:30
    at /Users/vwrobel/Projets/myApp/node_modules/webpack/lib/NormalModuleFactory.js:63:13
    at NormalModuleFactory.applyPluginsAsyncWaterfall (/Users/vwrobel/Projets/myApp/node_modules/tapable/lib/Tapable.js:123:70)
    at onDoneResolving (/Users/vwrobel/Projets/myApp/node_modules/webpack/lib/NormalModuleFactory.js:38:11)
    at onDoneResolving (/Users/vwrobel/Projets/myApp/node_modules/webpack/lib/NormalModuleFactory.js:135:6)
    at /Users/vwrobel/Projets/myApp/node_modules/webpack/lib/NormalModuleFactory.js:130:7
    at /Users/vwrobel/Projets/myApp/node_modules/async/lib/async.js:726:13
    at /Users/vwrobel/Projets/myApp/node_modules/async/lib/async.js:52:16
    at async.forEachOf.async.eachOf (/Users/vwrobel/Projets/myApp/node_modules/async/lib/async.js:236:30)
```

`webpack-externals-plugin` seems to be linked to this issue but I do not have a clue of what to do.

**Comment by froskie** [comment] 2016-07-22 17:51
The **Chunk.entry was removed. Use hasRuntime()** is fixed by changing **line 26** in
`node_modules/chunk-manifest-webpack-plugin/lib/ChunkManifestlugin.js`
by changing `if(c.entry)` to `if(c.hasRuntime()`.
(fork the project, obviously)

The **TypeError: Cannot read property 'request' of undefined** is fixed by changing **line 16** in
`node_modules/webpack-externals-plugin/index.js`
by changing `data.dependency.request` to `data.dependencies.request`
(fork the project, obviously)

**Comment by vwrobel** [comment] 2016-07-22 18:13
@froskie: Thank you for your answer!

I had tried this and `build:server` indeed runs fine but then `start:prod` throws the following error:

```

> mern-starter@2.0.0 start:prod /Users/vwrobel/Projets/myApp
> cross-env NODE_ENV=production node index.js


assert.js:90
  throw new assert.AssertionError({
  ^
AssertionError: missing path
    at Module.require (module.js:466:3)
    at require (internal/module.js:20:19)
    at Object.defineProperty.value (/Users/vwrobel/Projets/myApp/dist/server.bundle.js:71:18)
    at __webpack_require__ (/Users/vwrobel/Projets/myApp/dist/server.bundle.js:20:30)
    at Object.<anonymous> (/Users/vwrobel/Projets/myApp/dist/server.bundle.js:1868:16)
    at Object.<anonymous> (/Users/vwrobel/Projets/myApp/dist/server.bundle.js:2036:30)
    at __webpack_require__ (/Users/vwrobel/Projets/myApp/dist/server.bundle.js:20:30)
    at /Users/vwrobel/Projets/myApp/dist/server.bundle.js:64:18
    at Object.<anonymous> (/Users/vwrobel/Projets/myApp/dist/server.bundle.js:67:10)
    at Module._compile (module.js:541:32)

npm ERR! Darwin 15.5.0
npm ERR! argv "/usr/local/bin/node" "/usr/local/bin/npm" "run" "start:prod"
npm ERR! node v6.2.0
npm ERR! npm  v3.9.6
npm ERR! code ELIFECYCLE
npm ERR! mern-starter@2.0.0 start:prod: `cross-env NODE_ENV=production node index.js`
npm ERR! Exit status 1
```

Thank you for your help!

**Comment by froskie** [comment] 2016-07-22 19:52
@vwrobel just fixed mine here and updated the comment. `dependencies` are now an array.

**Comment by vwrobel** [comment] 2016-07-22 20:07
@froskie great! Glad you found this fix!

**Comment by Pokom** [comment] 2016-07-23 18:02
@froskie That did the trick. 

Is there any thoughts on how we can fix this? Otherwise I'd be willing to document the process and add it to the FAQ's until it's been resolved.

**Comment by froskie** [comment] 2016-07-25 14:19
@Pokom not really, since it's libraries that we depend on that are causing the issues.

**Comment by Pokom** [comment] 2016-07-25 14:29
@froskie That is true, but in the meantime the mern-starter requires a few hacks in place to get the build to work properly. I would imagine this isn't an ideal situation for new users(like myself) looking to deploy for the first time. 

It might even be as simple as adding in the README.md until the build scripts a reference to your suggested work around until the dependencies fix their projects.

**Comment by maciejmyslinski** [comment] 2016-07-25 19:08
@froskie @Pokom I think it's totally possible.

`package.json`
```diff
- "chunk-manifest-webpack-plugin": "0.1.0",
+ "chunk-manifest-webpack-plugin": "https://github.com/brandondoran/chunk-manifest-webpack-plugin/tarball/f60e59a95fccdedbb617c6437cc9dd0a3773dd46",

- "extract-text-webpack-plugin": "1.0.1",
+ "extract-text-webpack-plugin": "^2.0.0-beta",

- "webpack": "2.1.0-beta.8",
+ "webpack": "^2.1.0-beta.20",

- "webpack-externals-plugin": "^1.0.0",
+ "webpack-externals-plugin": "https://github.com/goalgoodies/webpack-externals-plugin/tarball/fafe508019e8b46fac09947048c4e0ef3e0ed369",
```

`webpack.config.prod.js`
```diff
-        loader: ExtractTextPlugin.extract('style-loader', 'css-loader?localIdentName=[hash:base64]&modules&importLoaders=1!postcss-loader'),
+        loader: ExtractTextPlugin.extract({
+          fallbackLoader: 'style-loader',
+          loader: 'css-loader?localIdentName=[hash:base64]&modules&importLoaders=1!postcss-loader'
+        }),

-    new ExtractTextPlugin('app.[chunkhash].css', { allChunks: true }),
+    new ExtractTextPlugin({
+      filename: 'app.[chunkhash].css',
+      allChunks: true,
+    }),
```

I know it is temporary hack over dependencies, but works.
What do you think?

**Comment by suvorovu** [comment] 2016-08-14 20:19
I fixed the issue by 
`npm install node-libs-browser@^1.0.0 -S`

**Closed** 2018-06-02 04:52 UTC
