### ISSUE TITLE
Chunk.entry was removed. Use hasRuntime()

### ISSUE THREAD

**Issue by maciejmyslinski** [Hashnode/mern-starter#206] opened 2016-07-20 09:59 UTC
When `npm run build` I get an error:

```bash
mern-starter/node_modules/webpack/lib/Chunk.js:34
		throw new Error("Chunk.entry was removed. Use hasRuntime()");
		^

Error: Chunk.entry was removed. Use hasRuntime()
```

**Comment by maciejmyslinski** [comment] 2016-07-20 10:30
Seems to be connected with [this](https://github.com/webpack/webpack/issues/2764)

**Comment by maciejmyslinski** [comment] 2016-07-20 10:48
Upgradeing `extract-text-webpack-plugin` to `2.0.0-beta` did created another error:

```bash


Hash: fd106acedb6720cd4deb
Version: webpack 2.1.0-beta.19
Time: 5982ms
                               Asset       Size  Chunks             Chunk Names
bbaeb5f32b7042f0def39648a1d111b9.png    15.8 kB          [emitted]
           0.0b6ea5954dbb8827a07d.js    7.93 kB       0  [emitted]
           1.783f24e8954bb10c38c6.js     1.8 kB       1  [emitted]
         app.dde9800e8a5fd2568e1c.js     375 kB       2  [emitted]  app
        app.dde9800e8a5fd2568e1c.css    3.04 kB       2  [emitted]  app
    app.dde9800e8a5fd2568e1c.css.map  105 bytes       2  [emitted]  app
                       manifest.json  334 bytes          [emitted]
 [645] multi app 28 bytes {2} [built]
 [646] multi vendor 40 bytes {3} [built]
    + 652 hidden modules

ERROR in chunk vendor [entry]
app.dde9800e8a5fd2568e1c.js
Chunk.entry was removed. Use hasRuntime()
Child extract-text-webpack-plugin:
        + 2 hidden modules
Child extract-text-webpack-plugin:
        + 2 hidden modules
Child extract-text-webpack-plugin:
        + 2 hidden modules
Child extract-text-webpack-plugin:
        + 2 hidden modules
Child extract-text-webpack-plugin:
        + 2 hidden modules
Child extract-text-webpack-plugin:
        + 3 hidden modules
```

**Comment by somus** [comment] 2016-07-21 03:44
Duplicate of #200

**Closed by somus** 2016-07-21 03:44 UTC
