### ISSUE TITLE
Markup different on the server and the client

### ISSUE THREAD

**Issue by ile** [Hashnode/mern-starter#149] opened 2016-05-29 04:07 UTC
I'm new with MERN, so not sure if I'm doing something wrong.... but, I get this:

```
warning.js?8a56:44Warning: React attempted to reuse markup in a container but the checksum was invalid. This generally means that you are using server rendering and the markup generated on the server was not what the client was expecting. React injected new markup to compensate which works but you have lost many of the benefits of server rendering. Instead, figure out why the markup being generated is different on the client or server:
 (client) " data-reactid="1"><div data-reactid="2"
 (server) " data-reactid="1"><!-- react-empty: 2 -
```

Seems like the markup is otherwise the same, but there is this extra comment `<!-- react-empty: 2 -->` just after `<div data-reactroot="" data-reactid="1" data-react-checksum="1358521740">`, on the server side.

This seems to happen if I create the project with `mern` executable and use that and also if I clone the 2.0 branch and use that...

**Comment by lubien** [comment] 2016-05-30 07:59
Last time I got this (I wasn't using mern.io) the cause was my server rendering my component without it having the initial data that was retrieved async. But in the client it had time to get the data and rendered differently from the server.

**Comment by joernroeder** [comment] 2016-05-30 09:00
Maybe related https://github.com/Hashnode/mern-starter/issues/139

**Comment by somus** [comment] 2016-05-31 10:56
There is a problem in v2 branch after implementing react-router code splitting. Initially, the client is generating an empty response which is not matching with the server response. That's why this warning comes. But, everything works as expected.

**Comment by SOSANA** [comment] 2016-06-24 22:54
@somus  will be doing pr shortly to fix this, as well as error not rendering header png

**Comment by SOSANA** [comment] 2016-06-24 23:13
PR #181 ready for your review @somus 
sorry about to commits to index.js accidently forgot closing curly brace as I  was in rush to grab kids from school :(

**Comment by SOSANA** [comment] 2016-06-25 01:05
@somus closing last PR, only doing one PR to fix this bug, next will be to fix png issue in header, and another PR to fix inital render of client before server

**Comment by colinshen** [comment] 2016-06-30 17:43
I'm using mern.io with react bootstrap. I'm getting this warning, and source codes are totally different from client and server rendering. is there are way to fix this with react bootstrap?

**Comment by code4aman** [comment] 2016-07-12 11:23
Small workaround could be something like that:
instead of
```javascript
<div id="root">${html}</div>
```
paste this
```javascript
<div id="root">${process.env.NODE_ENV === 'production' ? html : `<div>${html}</div>`}</div>
```
at [server/server.js#L80](https://github.com/Hashnode/mern-starter/blob/master/server/server.js#L80)
:ok_hand: so you'll get rid of this warning on dev mode (if you are using Redux DevTools) and keep production markup unchanged.

**Comment by quocble** [comment] 2017-04-06 22:54
```
<div id="root">${process.env.NODE_ENV === 'production' ? html : `<div>${html}</div>`}</div>
```
should be part of the official build..

**Comment by damorton** [comment] 2017-05-11 08:55
Use templating on the server side to inject the data into the html view that would be collected on the client side before serving the html to the client.

**Comment by MrChristofferson** [comment] 2018-06-04 04:19
Fixed by https://github.com/Hashnode/mern-starter/pull/369 and in `upgrade/2.4.0` branch.

**Closed by MrChristofferson** 2018-06-04 04:19 UTC
Labels: bug, help wanted
